from pathlib import Path
import joblib
import pandas as pd
from .config import FEATURES
from .schema import Customer


def load_bundle(path):
    # joblib uses pickle: load only artifacts generated by this trusted project.
    bundle = joblib.load(Path(path))
    if bundle.get("features") != FEATURES:
        raise ValueError("Artifact feature schema does not match the application")
    return bundle


def predict_customer(bundle, customer: Customer):
    row = customer.model_dump()
    if row["TotalCharges"] is None:
        row["TotalCharges"] = float("nan")
    probability = float(
        bundle["pipeline"].predict_proba(pd.DataFrame([row], columns=FEATURES))[0, 1]
    )
    high = probability >= bundle["threshold"]
    return {
        "churn_probability": probability,
        "risk": "High" if high else "Low",
        "predicted_churn": high,
        "threshold": bundle["threshold"],
        "model": bundle["model_name"],
        "dataset": bundle["dataset"],
    }
